model:
  _target_: quadra.models.classification.TimmNetworkBuilder
  model_name: vit_small_patch16_dinov3
  pretrained: true
  freeze: false
metadata:
  input_size: 224
  output_dim: 384
  patch_size: 16
  nb_heads: 6
