model:
  _target_: quadra.models.classification.TimmNetworkBuilder
  model_name: edgenext_small.usi_in1k
  pretrained: true
  freeze: false
metadata:
  input_size: 256
  output_dim: 304
  nb_heads: 8
