model:
  _target_: quadra.models.classification.TimmNetworkBuilder
  model_name: mobilenet_edgetpu_v2_m.ra4_e3600_r224_in1k
  pretrained: true
  freeze: false
metadata:
  input_size: 224
  output_dim: 1344
