model:
  _target_: quadra.models.classification.TimmNetworkBuilder
  model_name: repvit_m1_1.dist_450e_in1k
  pretrained: true
  freeze: false
metadata:
  input_size: 224
  output_dim: 512
  patch_size: 4
  nb_heads: 8
