_target_: pytorch_lightning.Trainer
accelerator: gpu
devices: [0]
min_epochs: 1
max_epochs: 10
log_every_n_steps: 10
precision: bf16
strategy: auto
num_nodes: 1
fast_dev_run: false
max_time:
limit_train_batches:
limit_val_batches:
limit_test_batches:
limit_predict_batches:
overfit_batches: 0.0
val_check_interval:
check_val_every_n_epoch: 1
num_sanity_val_steps:
enable_checkpointing:
enable_progress_bar:
enable_model_summary:
accumulate_grad_batches: 1
gradient_clip_val:
gradient_clip_algorithm:
deterministic:
benchmark:
inference_mode: True
use_distributed_sampler: True
profiler:
detect_anomaly: False
barebones: False
plugins:
sync_batchnorm: False
reload_dataloaders_every_n_epochs: 0
default_root_dir:
