version:
  _target_: quadra.get_version
seed: 42
tag: null
name: null
cv2_num_threads: 1
command: "python "
experiment_path: null
upload_artifacts: False
upload_models: ${export.types} # Default behavior in quadra <= 1.5.6
log_level: info
mlflow_zip_models: False
